### ISSUE TITLE
QA_Functions_Further readings_broken link

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#70] opened 2016-11-03 10:47 UTC
Defect Description:
In the Further Readings page of "Functions" experiment of this lab, the 2nd link is broken. The link should be either replaced or removed.

Actual Result :
In the Further Readings page of "Functions" experiment of this lab, the 2nd link is broken.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i13](https://cloud.githubusercontent.com/assets/13479177/19963054/8c3b1eb8-a1dc-11e6-914f-8354c2827060.png)

**Comment by sravanthimodepu** [comment] 2017-05-18 12:41
Link is updated and the issue is fixed now.

**Closed** 2018-10-12 07:34 UTC
Labels: Open-Edx-Issue, Status: Open
