### ISSUE TITLE
QA_Array_Simulation_page redirecting to error page

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#64] opened 2016-11-03 10:23 UTC
Defect Description:
In the experiment page of "Arrays" of this lab, in the simulation segment when we click on Experiment icon from Quiz page, the page is navigating to error page. Where as the page should navigate to the appropriate page.

Actual Result :
In the experiment page of "Arrays" of this lab, in the simulation segment when we click on Experiment icon from Quiz page, the page is navigating to error page. 

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i7](https://cloud.githubusercontent.com/assets/13479177/19962440/668f63d4-a1d9-11e6-9f35-84a000d2ee74.png)

**Comment by sravanthimodepu** [comment] 2017-05-18 11:48
Link is updated and the issue is fixed now.

**Closed** 2018-10-12 07:34 UTC
Labels: Developed By: VLEAD, Open-Edx-Issue, Resolved, Status: Open
